export enum BaselinesPanelsEnum {
  WAITING_MY_EVALUATION = 'WAITING_MY_EVALUATION',
  WAITING_OTHERS_EVALUATIONS = 'WAITING_OTHERS_EVALUATIONS',
  APPROVEDS = 'APPROVEDS',
  REJECTEDS = 'REJECTEDS',
}