export enum DeliverableStatus {
  ACOES_PREPARATORIAS = 'Ações preparatórias',
  PROJETO_EM_ELABORACAO = 'Projeto em elaboração',
  PROJETO_ELABORADO = 'Projeto elaborado',
  CONVENIO_ASSINADO = 'Convênio assinado',
  EDITAL_PUBLICADO = 'Edital publicado',
  LICITACAO_CONCLUIDA = 'Licitação concluída',
  CONTRATO_ASSINADO = 'Contrato assinado',
  OBRA_EM_ANDAMENTO = 'Obra em andamento',
  SERVICO_EM_ANDAMENTO = 'Serviço em andamento',
  CONCLUIDA = 'Concluída',
  SUSPENSA = 'Suspensa',
  EM_EXECUCAO = 'Em execução',
  PARALISADO = 'Paralisado',
  EM_LICITACAO = 'Em licitação',
  CANCELADA = 'Cancelada',
  A_LICITAR = 'A licitar',
  A_CANCELAR = 'A cancelar',
}
