export enum StatusJournalEnum {
  EDITED = 'edited',
  CREATED = 'created',
  REMOVED = 'removed',
  CANCELLED = 'cancelled',
  DRAFT = 'draft',
  PROPOSED = 'proposed',
  REJECTED = 'rejected',
  APPROVED = 'approved',
  OPEN = 'open',
  CLOSED = 'closed',
  WAITING = 'waiting',
  RUNNING = 'running',
  DONE = 'done',
  NOT_GONNA_HAPPEN = 'notGonnaHappen',
  HAPPENED = 'happened',
  WAITING_TRIGGER = 'waitingTrigger',
}
