export enum TypeJournalEnum {
  INFORMATION = 'information',
  DATE_CHANGED = 'dateChanged', 
  EDITION = 'edition',
  FAIL = 'failure',
  BASELINE = 'baseline',
  ISSUE = 'issue',
  ISSUE_RESPONSE = 'issueResponse',
  RISK = 'risk',
  RISK_RESPONSE = 'riskResponse',
  OFFICE_PERMISSION = 'officePermission',
  PLAN_PERMISSION =  'planPermission',
  WORKPACK_PERMISSION = 'workpackPermission',
  ALL = 'all',
}
