export const IconsSolidEng = [
  'ad',
  'address-book',
  'address-card',
  'adjust',
  'air-freshener',
  'align-center',
  'align-justify',
  'align-left',
  'align-right',
  'allergies',
  'ambulance',
  'american-sign-language-interpreting',
  'anchor',
  'angle-double-down',
  'angle-double-left',
  'angle-double-right',
  'angle-double-up',
  'angle-down',
  'angle-left',
  'angle-right',
  'angle-up',
  'angry',
  'ankh',
  'apple-alt',
  'archive',
  'archway',
  'arrow-alt-circle-down',
  'arrow-alt-circle-left',
  'arrow-alt-circle-right',
  'arrow-alt-circle-up',
  'arrow-circle-down',
  'arrow-circle-left',
  'arrow-circle-right',
  'arrow-circle-up',
  'arrow-down',
  'arrow-left',
  'arrow-right',
  'arrow-up',
  'arrows-alt',
  'arrows-alt-h',
  'arrows-alt-v',
  'assistive-listening-systems',
  'asterisk',
  'at',
  'atlas',
  'atom',
  'audio-description',
  'award',
  'baby',
  'baby-carriage',
  'backspace',
  'backward',
  'bacon',
  'bacteria',
  'bacterium',
  'bahai',
  'balance-scale',
  'balance-scale-left',
  'balance-scale-right',
  'ban',
  'band-aid',
  'barcode',
  'bars',
  'baseball-ball',
  'basketball-ball',
  'bath',
  'battery-empty',
  'battery-full',
  'battery-half',
  'battery-quarter',
  'battery-three-quarters',
  'bed',
  'beer',
  'bell',
  'bell-slash',
  'bezier-curve',
  'bible',
  'bicycle',
  'biking',
  'binoculars',
  'biohazard',
  'birthday-cake',
  'blender',
  'blender-phone',
  'blind',
  'blog',
  'bold',
  'bolt',
  'bomb',
  'bone',
  'bong',
  'book',
  'book-dead',
  'book-medical',
  'book-open',
  'book-reader',
  'bookmark',
  'border-all',
  'border-none',
  'border-style',
  'bowling-ball',
  'box',
  'box-open',
  'box-tissue',
  'boxes',
  'braille',
  'brain',
  'bread-slice',
  'briefcase',
  'briefcase-medical',
  'broadcast-tower',
  'broom',
  'brush',
  'bug',
  'building',
  'bullhorn',
  'bullseye',
  'burn',
  'bus',
  'bus-alt',
  'business-time',
  'calculator',
  'calendar',
  'calendar-alt',
  'calendar-check',
  'calendar-day',
  'calendar-minus',
  'calendar-plus',
  'calendar-times',
  'calendar-week',
  'camera',
  'camera-retro',
  'campground',
  'candy-cane',
  'cannabis',
  'capsules',
  'car',
  'car-alt',
  'car-battery',
  'car-crash',
  'car-side',
  'caravan',
  'caret-down',
  'caret-left',
  'caret-right',
  'caret-square-down',
  'caret-square-left',
  'caret-square-right',
  'caret-square-up',
  'caret-up',
  'carrot',
  'cart-arrow-down',
  'cart-plus',
  'cash-register',
  'cat',
  'certificate',
  'chair',
  'chalkboard',
  'chalkboard-teacher',
  'charging-station',
  'chart-area',
  'chart-bar',
  'chart-line',
  'chart-pie',
  'check',
  'check-circle',
  'check-double',
  'check-square',
  'cheese',
  'chess',
  'chess-bishop',
  'chess-board',
  'chess-king',
  'chess-knight',
  'chess-pawn',
  'chess-queen',
  'chess-rook',
  'chevron-circle-down',
  'chevron-circle-left',
  'chevron-circle-right',
  'chevron-circle-up',
  'chevron-down',
  'chevron-left',
  'chevron-right',
  'chevron-up',
  'child',
  'church',
  'circle',
  'circle-notch',
  'city',
  'clinic-medical',
  'clipboard',
  'clipboard-check',
  'clipboard-list',
  'clock',
  'clone',
  'closed-captioning',
  'cloud',
  'cloud-download-alt',
  'cloud-meatball',
  'cloud-moon',
  'cloud-moon-rain',
  'cloud-rain',
  'cloud-showers-heavy',
  'cloud-sun',
  'cloud-sun-rain',
  'cloud-upload-alt',
  'cocktail',
  'code',
  'code-branch',
  'coffee',
  'cog',
  'cogs',
  'coins',
  'columns',
  'comment',
  'comment-alt',
  'comment-dollar',
  'comment-dots',
  'comment-medical',
  'comment-slash',
  'comments',
  'comments-dollar',
  'compact-disc',
  'compass',
  'compress',
  'compress-alt',
  'compress-arrows-alt',
  'concierge-bell',
  'cookie',
  'cookie-bite',
  'copy',
  'copyright',
  'couch',
  'credit-card',
  'crop',
  'crop-alt',
  'cross',
  'crosshairs',
  'crow',
  'crown',
  'crutch',
  'cube',
  'cubes',
  'cut',
  'database',
  'deaf',
  'democrat',
  'desktop',
  'dharmachakra',
  'diagnoses',
  'dice',
  'dice-d20',
  'dice-d6',
  'dice-five',
  'dice-four',
  'dice-one',
  'dice-six',
  'dice-three',
  'dice-two',
  'digital-tachograph',
  'directions',
  'disease',
  'divide',
  'dizzy',
  'dna',
  'dog',
  'dollar-sign',
  'dolly',
  'dolly-flatbed',
  'donate',
  'door-closed',
  'door-open',
  'dot-circle',
  'dove',
  'download',
  'drafting-compass',
  'dragon',
  'draw-polygon',
  'drum',
  'drum-steelpan',
  'drumstick-bite',
  'dumbbell',
  'dumpster',
  'dumpster-fire',
  'dungeon',
  'edit',
  'egg',
  'eject',
  'ellipsis-h',
  'ellipsis-v',
  'envelope',
  'envelope-open',
  'envelope-open-text',
  'envelope-square',
  'equals',
  'eraser',
  'ethernet',
  'euro-sign',
  'exchange-alt',
  'exclamation',
  'exclamation-circle',
  'exclamation-triangle',
  'expand',
  'expand-alt',
  'expand-arrows-alt',
  'external-link-alt',
  'external-link-square-alt',
  'eye',
  'eye-dropper',
  'eye-slash',
  'fan',
  'fast-backward',
  'fast-forward',
  'faucet',
  'fax',
  'feather',
  'feather-alt',
  'female',
  'fighter-jet',
  'file',
  'file-alt',
  'file-archive',
  'file-audio',
  'file-code',
  'file-contract',
  'file-csv',
  'file-download',
  'file-excel',
  'file-export',
  'file-image',
  'file-import',
  'file-invoice',
  'file-invoice-dollar',
  'file-medical',
  'file-medical-alt',
  'file-pdf',
  'file-powerpoint',
  'file-prescription',
  'file-signature',
  'file-upload',
  'file-video',
  'file-word',
  'fill',
  'fill-drip',
  'film',
  'filter',
  'fingerprint',
  'fire',
  'fire-alt',
  'fire-extinguisher',
  'first-aid',
  'fish',
  'fist-raised',
  'flag',
  'flag-checkered',
  'flag-usa',
  'flask',
  'flushed',
  'folder',
  'folder-minus',
  'folder-open',
  'folder-plus',
  'font',
  'football-ball',
  'forward',
  'frog',
  'frown',
  'frown-open',
  'funnel-dollar',
  'futbol',
  'gamepad',
  'gas-pump',
  'gavel',
  'gem',
  'genderless',
  'ghost',
  'gift',
  'gifts',
  'glass-cheers',
  'glass-martini',
  'glass-martini-alt',
  'glass-whiskey',
  'glasses',
  'globe',
  'globe-africa',
  'globe-americas',
  'globe-asia',
  'globe-europe',
  'golf-ball',
  'gopuram',
  'graduation-cap',
  'greater-than',
  'greater-than-equal',
  'grimace',
  'grin',
  'grin-alt',
  'grin-beam',
  'grin-beam-sweat',
  'grin-hearts',
  'grin-squint',
  'grin-squint-tears',
  'grin-stars',
  'grin-tears',
  'grin-tongue',
  'grin-tongue-squint',
  'grin-tongue-wink',
  'grin-wink',
  'grip-horizontal',
  'grip-lines',
  'grip-lines-vertical',
  'grip-vertical',
  'guitar',
  'h-square',
  'hamburger',
  'hammer',
  'hamsa',
  'hand-holding',
  'hand-holding-heart',
  'hand-holding-medical',
  'hand-holding-usd',
  'hand-holding-water',
  'hand-lizard',
  'hand-middle-finger',
  'hand-paper',
  'hand-peace',
  'hand-point-down',
  'hand-point-left',
  'hand-point-right',
  'hand-point-up',
  'hand-pointer',
  'hand-rock',
  'hand-scissors',
  'hand-sparkles',
  'hand-spock',
  'hands',
  'hands-helping',
  'hands-wash',
  'handshake',
  'handshake-alt-slash',
  'handshake-slash',
  'hanukiah',
  'hard-hat',
  'hashtag',
  'hat-cowboy',
  'hat-cowboy-side',
  'hat-wizard',
  'hdd',
  'head-side-cough',
  'head-side-cough-slash',
  'head-side-mask',
  'head-side-virus',
  'heading',
  'headphones',
  'headphones-alt',
  'headset',
  'heart',
  'heart-broken',
  'heartbeat',
  'helicopter',
  'highlighter',
  'hiking',
  'hippo',
  'history',
  'hockey-puck',
  'holly-berry',
  'home',
  'horse',
  'horse-head',
  'hospital',
  'hospital-alt',
  'hospital-symbol',
  'hospital-user',
  'hot-tub',
  'hotdog',
  'hotel',
  'hourglass',
  'hourglass-end',
  'hourglass-half',
  'hourglass-start',
  'house-damage',
  'house-user',
  'hryvnia',
  'i-cursor',
  'ice-cream',
  'icicles',
  'icons',
  'id-badge',
  'id-card',
  'id-card-alt',
  'igloo',
  'image',
  'images',
  'inbox',
  'indent',
  'industry',
  'infinity',
  'info',
  'info-circle',
  'italic',
  'jedi',
  'joint',
  'journal-whills',
  'kaaba',
  'key',
  'keyboard',
  'khanda',
  'kiss',
  'kiss-beam',
  'kiss-wink-heart',
  'kiwi-bird',
  'landmark',
  'language',
  'laptop',
  'laptop-code',
  'laptop-house',
  'laptop-medical',
  'laugh',
  'laugh-beam',
  'laugh-squint',
  'laugh-wink',
  'layer-group',
  'leaf',
  'lemon',
  'less-than',
  'less-than-equal',
  'level-down-alt',
  'level-up-alt',
  'life-ring',
  'lightbulb',
  'link',
  'lira-sign',
  'list',
  'list-alt',
  'list-ol',
  'list-ul',
  'location-arrow',
  'lock',
  'lock-open',
  'long-arrow-alt-down',
  'long-arrow-alt-left',
  'long-arrow-alt-right',
  'long-arrow-alt-up',
  'low-vision',
  'luggage-cart',
  'lungs',
  'lungs-virus',
  'magic',
  'magnet',
  'mail-bulk',
  'male',
  'map',
  'map-marked',
  'map-marked-alt',
  'map-marker',
  'map-marker-alt',
  'map-pin',
  'map-signs',
  'marker',
  'mars',
  'mars-double',
  'mars-stroke',
  'mars-stroke-h',
  'mars-stroke-v',
  'mask',
  'medal',
  'medkit',
  'meh',
  'meh-blank',
  'meh-rolling-eyes',
  'memory',
  'menorah',
  'mercury',
  'meteor',
  'microchip',
  'microphone',
  'microphone-alt',
  'microphone-alt-slash',
  'microphone-slash',
  'microscope',
  'minus',
  'minus-circle',
  'minus-square',
  'mitten',
  'mobile',
  'mobile-alt',
  'money-bill',
  'money-bill-alt',
  'money-bill-wave',
  'money-bill-wave-alt',
  'money-check',
  'money-check-alt',
  'monument',
  'moon',
  'mortar-pestle',
  'mosque',
  'motorcycle',
  'mountain',
  'mouse',
  'mouse-pointer',
  'mug-hot',
  'music',
  'network-wired',
  'neuter',
  'newspaper',
  'not-equal',
  'notes-medical',
  'object-group',
  'object-ungroup',
  'oil-can',
  'om',
  'otter',
  'outdent',
  'pager',
  'paint-brush',
  'paint-roller',
  'palette',
  'pallet',
  'paper-plane',
  'paperclip',
  'parachute-box',
  'paragraph',
  'parking',
  'passport',
  'pastafarianism',
  'paste',
  'pause',
  'pause-circle',
  'paw',
  'peace',
  'pen',
  'pen-alt',
  'pen-fancy',
  'pen-nib',
  'pen-square',
  'pencil-alt',
  'pencil-ruler',
  'people-arrows',
  'people-carry',
  'pepper-hot',
  'percent',
  'percentage',
  'person-booth',
  'phone',
  'phone-alt',
  'phone-slash',
  'phone-square',
  'phone-square-alt',
  'phone-volume',
  'photo-video',
  'piggy-bank',
  'pills',
  'pizza-slice',
  'place-of-worship',
  'plane',
  'plane-arrival',
  'plane-departure',
  'plane-slash',
  'play',
  'play-circle',
  'plug',
  'plus',
  'plus-circle',
  'plus-square',
  'podcast',
  'poll',
  'poll-h',
  'poo',
  'poo-storm',
  'poop',
  'portrait',
  'pound-sign',
  'power-off',
  'pray',
  'praying-hands',
  'prescription',
  'prescription-bottle',
  'prescription-bottle-alt',
  'print',
  'procedures',
  'project-diagram',
  'pump-medical',
  'pump-soap',
  'puzzle-piece',
  'qrcode',
  'question',
  'question-circle',
  'quidditch',
  'quote-left',
  'quote-right',
  'quran',
  'radiation',
  'radiation-alt',
  'rainbow',
  'random',
  'receipt',
  'record-vinyl',
  'recycle',
  'redo',
  'redo-alt',
  'registered',
  'remove-format',
  'reply',
  'reply-all',
  'republican',
  'restroom',
  'retweet',
  'ribbon',
  'ring',
  'road',
  'robot',
  'rocket',
  'route',
  'rss',
  'rss-square',
  'ruble-sign',
  'ruler',
  'ruler-combined',
  'ruler-horizontal',
  'ruler-vertical',
  'running',
  'rupee-sign',
  'sad-cry',
  'sad-tear',
  'satellite',
  'satellite-dish',
  'save',
  'school',
  'screwdriver',
  'scroll',
  'sd-card',
  'search',
  'search-dollar',
  'search-location',
  'search-minus',
  'search-plus',
  'seedling',
  'server',
  'shapes',
  'share',
  'share-alt',
  'share-alt-square',
  'share-square',
  'shekel-sign',
  'shield-alt',
  'shield-virus',
  'ship',
  'shipping-fast',
  'shoe-prints',
  'shopping-bag',
  'shopping-basket',
  'shopping-cart',
  'shower',
  'shuttle-van',
  'sign',
  'sign-in-alt',
  'sign-language',
  'sign-out-alt',
  'signal',
  'signature',
  'sim-card',
  'sink',
  'sitemap',
  'skating',
  'skiing',
  'skiing-nordic',
  'skull',
  'skull-crossbones',
  'slash',
  'sleigh',
  'sliders-h',
  'smile',
  'smile-beam',
  'smile-wink',
  'smog',
  'smoking',
  'smoking-ban',
  'sms',
  'snowboarding',
  'snowflake',
  'snowman',
  'snowplow',
  'soap',
  'socks',
  'solar-panel',
  'sort',
  'sort-alpha-down',
  'sort-alpha-down-alt',
  'sort-alpha-up',
  'sort-alpha-up-alt',
  'sort-amount-down',
  'sort-amount-down-alt',
  'sort-amount-up',
  'sort-amount-up-alt',
  'sort-down',
  'sort-numeric-down',
  'sort-numeric-down-alt',
  'sort-numeric-up',
  'sort-numeric-up-alt',
  'sort-up',
  'spa',
  'space-shuttle',
  'spell-check',
  'spider',
  'spinner',
  'splotch',
  'spray-can',
  'square',
  'square-full',
  'square-root-alt',
  'stamp',
  'star',
  'star-and-crescent',
  'star-half',
  'star-half-alt',
  'star-of-david',
  'star-of-life',
  'step-backward',
  'step-forward',
  'stethoscope',
  'sticky-note',
  'stop',
  'stop-circle',
  'stopwatch',
  'stopwatch-20',
  'store',
  'store-alt',
  'store-alt-slash',
  'store-slash',
  'stream',
  'street-view',
  'strikethrough',
  'stroopwafel',
  'subscript',
  'subway',
  'suitcase',
  'suitcase-rolling',
  'sun',
  'superscript',
  'surprise',
  'swatchbook',
  'swimmer',
  'swimming-pool',
  'synagogue',
  'sync',
  'sync-alt',
  'syringe',
  'table',
  'table-tennis',
  'tablet',
  'tablet-alt',
  'tablets',
  'tachometer-alt',
  'tag',
  'tags',
  'tape',
  'tasks',
  'taxi',
  'teeth',
  'teeth-open',
  'temperature-high',
  'temperature-low',
  'tenge',
  'terminal',
  'text-height',
  'text-width',
  'th',
  'th-large',
  'th-list',
  'theater-masks',
  'thermometer',
  'thermometer-empty',
  'thermometer-full',
  'thermometer-half',
  'thermometer-quarter',
  'thermometer-three-quarters',
  'thumbs-down',
  'thumbs-up',
  'thumbtack',
  'ticket-alt',
  'times',
  'times-circle',
  'tint',
  'tint-slash',
  'tired',
  'toggle-off',
  'toggle-on',
  'toilet',
  'toilet-paper',
  'toilet-paper-slash',
  'toolbox',
  'tools',
  'tooth',
  'torah',
  'torii-gate',
  'tractor',
  'trademark',
  'traffic-light',
  'trailer',
  'train',
  'tram',
  'transgender',
  'transgender-alt',
  'trash',
  'trash-alt',
  'trash-restore',
  'trash-restore-alt',
  'tree',
  'trophy',
  'truck',
  'truck-loading',
  'truck-monster',
  'truck-moving',
  'truck-pickup',
  'tshirt',
  'tty',
  'tv',
  'umbrella',
  'umbrella-beach',
  'underline',
  'undo',
  'undo-alt',
  'universal-access',
  'university',
  'unlink',
  'unlock',
  'unlock-alt',
  'upload',
  'user',
  'user-alt',
  'user-alt-slash',
  'user-astronaut',
  'user-check',
  'user-circle',
  'user-clock',
  'user-cog',
  'user-edit',
  'user-friends',
  'user-graduate',
  'user-injured',
  'user-lock',
  'user-md',
  'user-minus',
  'user-ninja',
  'user-nurse',
  'user-plus',
  'user-secret',
  'user-shield',
  'user-slash',
  'user-tag',
  'user-tie',
  'user-times',
  'users',
  'users-cog',
  'users-slash',
  'utensil-spoon',
  'utensils',
  'vector-square',
  'venus',
  'venus-double',
  'venus-mars',
  'vest',
  'vest-patches',
  'vial',
  'vials',
  'video',
  'video-slash',
  'vihara',
  'virus',
  'virus-slash',
  'viruses',
  'voicemail',
  'volleyball-ball',
  'volume-down',
  'volume-mute',
  'volume-off',
  'volume-up',
  'vote-yea',
  'vr-cardboard',
  'walking',
  'wallet',
  'warehouse',
  'water',
  'wave-square',
  'weight',
  'weight-hanging',
  'wheelchair',
  'wifi',
  'wind',
  'window-close',
  'window-maximize',
  'window-minimize',
  'window-restore',
  'wine-bottle',
  'wine-glass',
  'wine-glass-alt',
  'won-sign',
  'wrench',
  'x-ray',
  'yen-sign',
  'yin-yang',
];

export const IconsRegularEng = [
  'address-book',
  'address-card',
  'angry',
  'arrow-alt-circle-down',
  'arrow-alt-circle-left',
  'arrow-alt-circle-right',
  'arrow-alt-circle-up',
  'bell',
  'bell-slash',
  'bookmark',
  'building',
  'calendar',
  'calendar-alt',
  'calendar-check',
  'calendar-minus',
  'calendar-plus',
  'calendar-times',
  'caret-square-down',
  'caret-square-left',
  'caret-square-right',
  'caret-square-up',
  'chart-bar',
  'check-circle',
  'check-square',
  'circle',
  'clipboard',
  'clock',
  'clone',
  'closed-captioning',
  'comment',
  'comment-alt',
  'comment-dots',
  'comments',
  'compass',
  'copy',
  'copyright',
  'credit-card',
  'dizzy',
  'dot-circle',
  'edit',
  'envelope',
  'envelope-open',
  'eye',
  'eye-slash',
  'file',
  'file-alt',
  'file-archive',
  'file-audio',
  'file-code',
  'file-excel',
  'file-image',
  'file-pdf',
  'file-powerpoint',
  'file-video',
  'file-word',
  'flag',
  'flushed',
  'folder',
  'folder-open',
  'frown',
  'frown-open',
  'futbol',
  'gem',
  'grimace',
  'grin',
  'grin-alt',
  'grin-beam',
  'grin-beam-sweat',
  'grin-hearts',
  'grin-squint',
  'grin-squint-tears',
  'grin-stars',
  'grin-tears',
  'grin-tongue',
  'grin-tongue-squint',
  'grin-tongue-wink',
  'grin-wink',
  'hand-lizard',
  'hand-paper',
  'hand-peace',
  'hand-point-down',
  'hand-point-left',
  'hand-point-right',
  'hand-point-up',
  'hand-pointer',
  'hand-rock',
  'hand-scissors',
  'hand-spock',
  'handshake',
  'hdd',
  'heart',
  'hospital',
  'hourglass',
  'id-badge',
  'id-card',
  'image',
  'images',
  'keyboard',
  'kiss',
  'kiss-beam',
  'kiss-wink-heart',
  'laugh',
  'laugh-beam',
  'laugh-squint',
  'laugh-wink',
  'lemon',
  'life-ring',
  'lightbulb',
  'list-alt',
  'map',
  'meh',
  'meh-blank',
  'meh-rolling-eyes',
  'minus-square',
  'money-bill-alt',
  'moon',
  'newspaper',
  'object-group',
  'object-ungroup',
  'paper-plane',
  'pause-circle',
  'play-circle',
  'plus-square',
  'question-circle',
  'registered',
  'sad-cry',
  'sad-tear',
  'save',
  'share-square',
  'smile',
  'smile-beam',
  'smile-wink',
  'snowflake',
  'square',
  'star',
  'star-half',
  'sticky-note',
  'stop-circle',
  'sun',
  'surprise',
  'thumbs-down',
  'thumbs-up',
  'times-circle',
  'tired',
  'trash-alt',
  'user',
  'user-circle',
  'window-close',
  'window-maximize',
  'window-minimize',
  'window-restore',
];

export const IconsRegularPt = [
  'livro de endereços',
  'cartão de endereço',
  'Bravo',
  'seta circulada baixo',
  'seta circulada esquerda',
  'seta circulada direita',
  'seta circulada cima',
  'Sino',
  'barra de sino',
  'marca páginas',
  'construção',
  'calendário',
  'calendar-alt',
  'verificação do calendário',
  'sem calendário',
  'calendário mais',
  'tempos do calendário',
  'acento circunflexo',
  'acento circunflexo esquerdo',
  'acento circunflexo-direito',
  'acento circunflexo',
  'barra de gráfico',
  'círculo de verificação',
  'quadrado de verificação',
  'círculo',
  'prancheta',
  'relógio',
  'clone',
  'legendas fechadas',
  'comentario',
  'comentario',
  'comentários-pontos',
  'comentários',
  'bússola',
  'cópia de',
  'direito autoral',
  'cartão de crédito',
  'tonto',
  'ponto-círculo',
  'editar',
  'envelope',
  'envelope aberto',
  'olho',
  'barra de olho',
  'Arquivo',
  'arquivo-alt',
  'arquivo-arquivo',
  'arquivo de áudio',
  'código de arquivo',
  'arquivo-excel',
  'imagem-arquivo',
  'arquivo-pdf',
  'arquivo-powerpoint',
  'arquivo de vídeo',
  'palavra de arquivo',
  'bandeira',
  'ruborizado',
  'pasta',
  'pasta aberta',
  'carranca',
  'carrancudo',
  'futbol',
  'gema',
  'careta',
  'sorriso largo',
  'sorriso alt',
  'sorriso largo',
  'sorriso-feixe-suor',
  'corações sorridentes',
  'sorriso forçado',
  'riso-estrabismo-lágrimas',
  'estrelas sorridentes',
  'lágrimas sorridentes',
  'língua sorridente',
  'sorriso-língua-vesgo',
  'sorriso-língua-piscar',
  'piscadela',
  'lagarto de mão',
  'papel de mão',
  'mão-paz',
  'apontar para baixo',
  'mão-apontar-esquerda',
  'mão-apontar-direita',
  'mão apontando para cima',
  'apontador',
  'mão-pedra',
  'tesoura de mão',
  'mão-spock',
  'aperto de mão',
  'disco rígido',
  'coração',
  'hospital',
  'ampulheta',
  'crachá de identificação',
  'carteira de identidade',
  'imagem',
  'imagens',
  'teclado',
  'beijo',
  'beijinho',
  'beijo-pisca-coração',
  'rir',
  'risada',
  'risada',
  'risada piscadela',
  'limão',
  'anel de vida',
  'lâmpada',
  'lista',
  'mapa',
  'meh',
  'meh-branco',
  'meh-revirando os olhos',
  'menos quadrado',
  'dinheiro-conta-alt',
  'lua',
  'jornal',
  'grupo-objeto',
  'object-ungroup',
  'Avião de papel',
  'pausa-círculo',
  'círculo de brincadeira',
  'quadrado positivo',
  'círculo de perguntas',
  'registrado',
  'choro triste',
  'tristeza',
  'Salve ',
  'share-square',
  'sorriso',
  'sorriso radiante',
  'sorriso piscadela',
  'floco de neve',
  'quadrado',
  'Estrela',
  'meia estrela',
  'notas adesivas',
  'círculo de parada',
  'Sol',
  'surpresa',
  'polegares para baixo',
  'afirmativo',
  'círculo do tempo',
  'cansado',
  'lixo-alt',
  'do utilizador',
  'círculo do usuário',
  'janela fechada',
  'maximização da janela',
  'minimizar janela',
  'janela-restauração',
];

export const IconsSolidPt = [
  'de Anúncios',
  'livro de endereços',
  'cartão de endereço',
  'ajustar',
  'purificador de ar',
  'alinhar-centro',
  'alinhar-justificar',
  'alinhar à esquerda',
  'alinhar à direita',
  'alergias',
  'ambulância',
  'interpretação de língua de sinais americana',
  'âncora',
  'ângulo dobrado para baixo',
  'ângulo duplo esquerdo',
  'ângulo-duplo-direito',
  'ângulo dobrado',
  'ângulo para baixo',
  'ângulo esquerdo',
  'ângulo direito',
  'ângulo para cima',
  'Bravo',
  'ankh',
  'maçã-alt',
  'arquivo',
  'arco',
  'arrow-alt-circle-down',
  'arrow-alt-circle-left',
  'arrow-alt-circle-right',
  'arrow-alt-circle-up',
  'seta para baixo',
  'seta-círculo-esquerda',
  'seta-círculo-direita',
  'seta para cima',
  'seta para baixo',
  'seta para a esquerda',
  'seta para a direita',
  'seta para cima',
  'setas-alt',
  'setas-alt-h',
  'setas-alt-v',
  'sistemas de escuta',
  'asterisco',
  'em',
  'Atlas',
  'átomo',
  'audiodescrição',
  'prêmio',
  'bebê',
  'carrinho de bebê',
  'backspace',
  'para trás',
  'bacon',
  'bactérias',
  'bactéria',
  'Bahai',
  'balança',
  'balance-scale-left',
  'equilíbrio-escala-direita',
  'banimento',
  'curativo',
  'código de barras',
  'barras',
  'bola de beisebol',
  'Bola de basquete',
  'banho',
  'Bateria vazia',
  'bateria cheia',
  'meia bateria',
  'quarto de bateria',
  'bateria - três quartos',
  'cama',
  'Cerveja',
  'Sino',
  'barra de sino',
  'curva de Bezier',
  'Bíblia',
  'bicicleta',
  'andar de bicicleta',
  'binóculos',
  'risco biológico',
  'bolo de aniversário',
  'liquidificador',
  'liquidificador-telefone',
  'cego',
  'blog',
  'negrito',
  'parafuso',
  'bombear',
  'osso',
  'bongo',
  'livro',
  'livro morto',
  'livro médico',
  'livro aberto',
  'Leitor',
  'marca páginas',
  'limite-tudo',
  'border-none',
  'estilo de borda',
  'bola de boliche',
  'caixa',
  'caixa aberta',
  'lenço de papel',
  'caixas',
  'braille',
  'cérebro',
  'fatia de pão',
  'pasta',
  'maleta médica',
  'torre de transmissão',
  'vassoura',
  'escova',
  'erro',
  'construção',
  'megafone',
  'alvo',
  'queimar',
  'ônibus',
  'bus-alt',
  'horário comercial',
  'calculadora',
  'calendário',
  'calendar-alt',
  'verificação do calendário',
  'dia-calendário',
  'sem calendário',
  'calendário mais',
  'tempos do calendário',
  'semana do calendário',
  'Câmera',
  'câmera retro',
  'área de camping',
  'bengala',
  'cannabis',
  'cápsulas',
  'carro',
  'carro-alt',
  'bateria de carro',
  'acidente de carro',
  'lado do carro',
  'caravana',
  'acento circunflexo',
  'acento circunflexo esquerdo',
  'acento circunflexo',
  'acento circunflexo',
  'acento circunflexo esquerdo',
  'acento circunflexo-direito',
  'acento circunflexo',
  'acento circunflexo',
  'cenoura',
  'carrinho-seta para baixo',
  'carrinho mais',
  'caixa registradora',
  'gato',
  'certificado',
  'cadeira',
  'quadro-negro',
  'professor-quadro',
  'estação para carregar',
  'área do gráfico',
  'barra de gráfico',
  'linha do gráfico',
  'gráfico de pizza',
  'Verifica',
  'círculo de verificação',
  'cheque duplo',
  'quadrado de verificação',
  'queijo',
  'xadrez',
  'bispo de xadrez',
  'tabuleiro de xadrez',
  'Rei do Xadrez',
  'cavaleiro de xadrez',
  'peão de xadrez',
  'rainha do xadrez',
  'torre de xadrez',
  'chevron-circle-down',
  'divisa-círculo-esquerda',
  'chevron-circle-right',
  'chevron-circle-up',
  'chevron-down',
  'chevron-left',
  'chevron-right',
  'chevron-up',
  'criança',
  'Igreja',
  'círculo',
  'círculo',
  'cidade',
  'clínica médica',
  'prancheta',
  'verificação da área de transferência',
  'lista da área de transferência',
  'relógio',
  'clone',
  'legendas fechadas',
  'nuvem',
  'cloud-download-alt',
  'almôndega',
  'nuvem-lua',
  'nuvem-lua-chuva',
  'nuvem de chuva',
  'nuvens pesadas',
  'nuvem-sol',
  'nuvem-sol-chuva',
  'nuvem-upload-alt',
  'coquetel',
  'código',
  'ramo de código',
  'café',
  'engrenagem',
  'engrenagens',
  'moedas',
  'colunas',
  'Comente',
  'comment-alt',
  'dólar de comentário',
  'comentários-pontos',
  'comentário médico',
  'comentário-barra',
  'comentários',
  'dólar de comentários',
  'disco compacto',
  'bússola',
  'comprimir',
  'compress-alt',
  'compress-setas-alt',
  'porteiro',
  'bolacha',
  'mordida de biscoito',
  'cópia de',
  'direito autoral',
  'sofá',
  'cartão de crédito',
  'colheita',
  'crop-alt',
  'Cruz',
  'mira',
  'Corvo',
  'coroa',
  'muleta',
  'cubo',
  'cubos',
  'cortar',
  'base de dados',
  'surdo',
  'democrata',
  'Área de Trabalho',
  'dharmachacra',
  'diagnósticos',
  'dados',
  'dice-d20',
  'dice-d6',
  'dados-cinco',
  'dados-quatro',
  'dados um',
  'dados-seis',
  'dados três',
  'dados dois',
  'tacógrafo digital',
  'instruções',
  'doença',
  'dividir',
  'tonto',
  'DNA',
  'cachorro',
  'cifrão',
  'boneca',
  'carrinho de bebê',
  'doar',
  'Porta fechada',
  'porta aberta',
  'ponto-círculo',
  'pomba',
  'baixar',
  'Compasso de desenho',
  'Dragão',
  'desenhar polígono',
  'tambor',
  'tambor de aço',
  'mordida de coxinha',
  'haltere',
  'deposito de lixo',
  'lixeira',
  'masmorra',
  'editar',
  'ovo',
  'ejetar',
  'reticências-h',
  'reticências-v',
  'envelope',
  'envelope aberto',
  'envelope-aberto-texto',
  'envelope-quadrado',
  'é igual a',
  'borracha',
  'ethernet',
  'euro-sign',
  'troca-alt',
  'exclamação',
  'círculo de exclamação',
  'triângulo de exclamação',
  'expandir',
  'expand-alt',
  'expandir-setas-alt',
  'external-link-alt',
  'external-link-square-alt',
  'olho',
  'conta-gotas',
  'barra de olho',
  'ventilador',
  'retrocesso rápido',
  'avanço rápido',
  'torneira',
  'fax',
  'pena',
  'pena alt',
  'fêmea',
  'jato de combate',
  'Arquivo',
  'arquivo-alt',
  'arquivo-arquivo',
  'arquivo de áudio',
  'código de arquivo',
  'contrato de arquivo',
  'arquivo-csv',
  'Download do arquivo',
  'arquivo-excel',
  'exportar arquivo',
  'imagem-arquivo',
  'importação de arquivo',
  'arquivo-fatura',
  'arquivo-fatura-dólar',
  'arquivo médico',
  'arquivo-médico-alt',
  'arquivo-pdf',
  'arquivo-powerpoint',
  'prescrição de arquivo',
  'assinatura de arquivo',
  'upload de arquivo',
  'arquivo de vídeo',
  'palavra de arquivo',
  'preencher',
  'encher-pingar',
  'filme',
  'filtro',
  'impressão digital',
  'fogo',
  'fogo alt',
  'extintor de incêndio',
  'primeiros socorros',
  'peixe',
  'punho levantado',
  'bandeira',
  'xadrez',
  'bandeira-eua',
  'frasco',
  'ruborizado',
  'pasta',
  'pasta-menos',
  'pasta aberta',
  'pasta mais',
  'Fonte',
  'bola de futebol',
  'frente',
  'rã',
  'carranca',
  'carrancudo',
  'funil-dólar',
  'futbol',
  'controle',
  'bomba de gasolina',
  'martelo',
  'gema',
  'sem gênero',
  'fantasma',
  'presente',
  'presentes',
  'vivas',
  'copo de martini',
  'copo-martini-alt',
  'whisky de vidro',
  'óculos',
  'globo',
  'globo-áfrica',
  'globo-américas',
  'globo-ásia',
  'globo-europa',
  'bola de golfe',
  'gopuram',
  'chapéu de graduação',
  'Maior que',
  'maior que igual',
  'careta',
  'sorriso largo',
  'sorriso alt',
  'sorriso largo',
  'sorriso-feixe-suor',
  'corações sorridentes',
  'sorriso forçado',
  'riso-estrabismo-lágrimas',
  'estrelas sorridentes',
  'lágrimas sorridentes',
  'língua sorridente',
  'sorriso-língua-vesgo',
  'sorriso-língua-piscar',
  'piscadela',
  'empunhadura horizontal',
  'linhas de aderência',
  'grip-lines-vertical',
  'empunhadura vertical',
  'guitarra',
  'h-quadrado',
  'Hamburger',
  'martelo',
  'hamsa',
  'mãos dadas',
  'mão segurando coração',
  'mão-segurando-médica',
  'mão-segurando-usd',
  'mão segurando água',
  'lagarto de mão',
  'mão-dedo médio',
  'papel de mão',
  'mão-paz',
  'apontar para baixo',
  'mão-apontar-esquerda',
  'mão-apontar-direita',
  'mão apontando para cima',
  'apontador',
  'mão-pedra',
  'tesoura de mão',
  'brilhos de mão',
  'mão-spock',
  'mãos',
  'mãos ajudando',
  'lava-mãos',
  'aperto de mão',
  'handshake-alt-slash',
  'aperto de mão-barra',
  'Hanukiah',
  'capacete',
  'hashtag',
  'chapéu-cowboy',
  'chapéu de cowboy',
  'feiticeiro de chapéu',
  'disco rígido',
  'tosse de cabeça',
  'tosse do lado da cabeça',
  'máscara do lado da cabeça',
  'vírus do lado da cabeça',
  'título',
  'fones de ouvido',
  'fones de ouvido alt',
  'fone de ouvido',
  'coração',
  'coração partido',
  'batimento cardiaco',
  'helicóptero',
  'marcador',
  'caminhada',
  'hipopótamo',
  'história',
  'disco de hóquei',
  'azevinho',
  'casa',
  'cavalo',
  'cabeça de cavalo',
  'hospital',
  'hospital-alt',
  'símbolo de hospital',
  'usuário de hospital',
  'jacuzzi',
  'cachorro quente',
  'hotel',
  'ampulheta',
  'ponta de ampulheta',
  'ampulheta meia',
  'ampulheta',
  'dano doméstico',
  'usuário doméstico',
  'hryvnia',
  'i-cursor',
  'sorvete',
  'pingentes de gelo',
  'ícones',
  'crachá de identificação',
  'carteira de identidade',
  'id-card-alt',
  'iglu',
  'imagem',
  'imagens',
  'caixa de entrada',
  'recuar',
  'indústria',
  'infinidade',
  'informação',
  'círculo de informações',
  'itálico',
  'Jedi',
  'junta',
  'diários',
  'Kaaba',
  'chave',
  'teclado',
  'Khanda',
  'beijo',
  'beijinho',
  'beijo-pisca-coração',
  'pássaro kiwi',
  'marco',
  'língua',
  'computador portátil',
  'código do laptop',
  'casa de laptop',
  'laptop-médico',
  'rir',
  'risada',
  'risada',
  'risada piscadela',
  'camada-grupo',
  'folha',
  'limão',
  'Menor que',
  'menor que igual',
  'nível-baixo-alt',
  'level-up-alt',
  'anel de vida',
  'lâmpada',
  'ligação',
  'sinal de lira',
  'Lista',
  'list-alt',
  'lista-ol',
  'list-ul',
  'seta de localização',
  'fechadura',
  'fechadura aberta',
  'long-arrow-alt-down',
  'long-arrow-alt-left',
  'long-arrow-alt-right',
  'long-arrow-alt-up',
  'visão subnormal',
  'carrinho de bagagem',
  'pulmões',
  'pulmão-vírus',
  'Magia',
  'magnético',
  'mail-bulk',
  'masculino',
  'mapa',
  'marcado no mapa',
  'mapa-marcado-alt',
  'marcador de mapa',
  'map-marker-alt',
  'pino de mapa',
  'sinais de mapa',
  'marcador',
  'Marte',
  'marte-duplo',
  'marte-derrame',
  'marte-acidente vascular cerebral',
  'marte-derrame-v',
  'mascarar',
  'medalha',
  'kit médico',
  'meh',
  'meh-branco',
  'meh-revirando os olhos',
  'memória',
  'menorá',
  'mercúrio',
  'meteoro',
  'microchip',
  'microfone',
  'microfone alt',
  'microfone-alt-barra',
  'barra de microfone',
  'microscópio',
  'menos',
  'círculo negativo',
  'menos quadrado',
  'luva',
  'Móvel',
  'mobile-alt',
  'nota de dinheiro',
  'dinheiro-conta-alt',
  'onda de dinheiro',
  'dinheiro-conta-onda-alt',
  'cheque',
  'dinheiro-cheque-alt',
  'monumento',
  'lua',
  'pilão de almofariz',
  'mesquita',
  'motocicleta',
  'montanha',
  'rato',
  'ponteiro do mouse',
  'caneca quente',
  'música',
  'com fio de rede',
  'neutro',
  'jornal',
  'não igual',
  'notas médicas',
  'grupo-objeto',
  'object-ungroup',
  'lata de óleo',
  'om',
  'lontra',
  'afundar',
  'pager',
  'pincel',
  'rolo de pintura',
  'paleta',
  'palete',
  'Avião de papel',
  'clipe de papel',
  'caixa de pára-quedas',
  'parágrafo',
  'estacionamento',
  'Passaporte',
  'massasfarianismo',
  'colar',
  'pausa',
  'pausa-círculo',
  'pata',
  'Paz',
  'caneta',
  'pen-alt',
  'fantasia de caneta',
  'ponta da caneta',
  'caneta-quadrado',
  'lápis-alt',
  'lápis-régua',
  'flechas de pessoas',
  'transporte de pessoas',
  'picante',
  'por cento',
  'percentagem',
  'cabine pessoal',
  'telefone',
  'telefone alt',
  'barra de telefone',
  'quadrado de telefone',
  'telefone-quadrado-alt',
  'volume do telefone',
  'foto-video',
  'cofrinho',
  'comprimidos',
  'fatia de pizza',
  'local de culto',
  'avião',
  'chegada de avião',
  'partida de avião',
  'corte plano',
  'Toque',
  'círculo de brincadeira',
  'plugue',
  'mais',
  'círculo positivo',
  'quadrado positivo',
  'podcast',
  'votação',
  'poll-h',
  'cocô',
  'tempestade de cocô',
  'cocô',
  'retrato',
  'sinal de libra',
  'desligar',
  'orar',
  'mãos em oração',
  'prescrição',
  'Garrafa de prescrição',
  'prescrição-garrafa-alt',
  'impressão',
  'procedimentos',
  'diagrama do projeto',
  'bomba médica',
  'bomba de sabão',
  'peça de quebra-cabeças',
  'Código QR',
  'questão',
  'círculo de perguntas',
  'quadribol',
  'citação esquerda',
  'citar direito',
  'Alcorão',
  'radiação',
  'radiação-alt',
  'arco Iris',
  'aleatória',
  'recibo',
  'vinil-disco',
  'reciclar',
  'refazer',
  'refazer alt',
  'registrado',
  'remover formato',
  'resposta',
  'responder todos',
  'republicano',
  'Sanitário',
  'retuitar',
  'fita',
  'anel',
  'estrada',
  'robô',
  'foguete',
  'rota',
  'rss',
  'rss-square',
  'signo do rublo',
  'régua',
  'governante combinado',
  'régua horizontal',
  'régua vertical',
  'corrida',
  'signo de rupia',
  'choro triste',
  'tristeza',
  'satélite',
  'antena parabólica',
  'Salve ',
  'escola',
  'Chave de fenda',
  'rolagem',
  'cartão SD',
  'pesquisa',
  'dólar de pesquisa',
  'localização de busca',
  'pesquisar menos',
  'search-plus',
  'plantinha',
  'servidor',
  'formas',
  'compartilhar',
  'share-alt',
  'share-alt-square',
  'share-square',
  'símbolo do siclo',
  'escudo-alt',
  'vírus escudo',
  'navio',
  'envio rápido',
  'estampas de sapatos',
  'Bolsa de compras',
  'Cesta de compras',
  'carrinho de compras',
  'chuveiro',
  'van',
  'placa',
  'sign-in-alt',
  'linguagem de sinais',
  'sair-alt',
  'sinal',
  'assinatura',
  'cartão SIM',
  'Pia',
  'Mapa do site',
  'patinação',
  'esquiar',
  'esqui nórdico',
  'crânio',
  'ossos cruzados de caveira',
  'golpear',
  'trenó',
  'sliders-h',
  'sorriso',
  'sorriso radiante',
  'sorriso piscadela',
  'poluição',
  'fumar',
  'proibição de fumar',
  'SMS',
  'snowboard',
  'floco de neve',
  'boneco de neve',
  'limpa-neve',
  'Sabonete',
  'meias',
  'painel solar',
  'ordenar',
  'sort-alpha-down',
  'sort-alpha-down-alt',
  'sort-alpha-up',
  'sort-alpha-up-alt',
  'ordenar valor para baixo',
  'classificar-quantidade-para baixo-alt',
  'sort-amount-up',
  'sort-montante-up-alt',
  'ordenar',
  'ordenar numérico para baixo',
  'sort-numeric-down-alt',
  'ordenar numérico',
  'sort-numic-up-alt',
  'ordenar',
  'spa',
  'nave espacial',
  'verificação ortográfica',
  'aranha',
  'spinner',
  'mancha',
  'lata de spray',
  'quadrado',
  'quadrado cheio',
  'raiz quadrada alt',
  'carimbo',
  'Estrela',
  'estrela e crescente',
  'meia estrela',
  'estrela meio alt',
  'estrela de Davi',
  'estrela da vida',
  'Um passo atrás',
  'passo à frente',
  'estetoscópio',
  'notas adesivas',
  'Pare',
  'círculo de parada',
  'cronômetro',
  'cronômetro-20',
  'loja',
  'store-alt',
  'store-alt-slash',
  'barra',
  'corrente',
  'vista da rua',
  'tachado',
  'Stroopwafel',
  'subscrito',
  'metrô',
  'mala de viagem',
  'enrolando mala',
  'Sol',
  'sobrescrito',
  'surpresa',
  'livro de amostras',
  'nadador',
  'piscina',
  'sinagoga',
  'sincronizar',
  'sync-alt',
  'seringa',
  'mesa',
  'tênis de mesa',
  'tábua',
  'tablet-alt',
  'comprimidos',
  'tacômetro-alt',
  'etiqueta',
  'Tag',
  'fita',
  'tarefas',
  'Táxi',
  'dentes',
  'dentes abertos',
  'temperatura alta',
  'temperatura baixa',
  'tenge',
  'terminal',
  'altura do texto',
  'largura do texto',
  'º',
  'o grande',
  'ª lista',
  'máscaras de teatro',
  'termômetro',
  'termômetro vazio',
  'termômetro cheio',
  'termômetro meio',
  'termômetro quarto',
  'termômetro três quartos',
  'polegares para baixo',
  'afirmativo',
  'tachinha',
  'ticket-alt',
  'vezes',
  'círculo do tempo',
  'matiz',
  'matiz',
  'cansado',
  'desligar',
  'ligar',
  'banheiro',
  'papel higiênico',
  'barra de papel higiênico',
  'Caixa de ferramentas',
  'Ferramentas',
  'dente',
  'Torá',
  'Torii-Gate',
  'trator',
  'marca comercial',
  'semáforo',
  'reboque',
  'trem',
  'eléctrico',
  'transgênero',
  'transgênero-alt',
  'Lixo',
  'trash-alt',
  'restauração de lixo',
  'trash-restore-alt',
  'árvore',
  'troféu',
  'caminhão',
  'carregamento de caminhão',
  'caminhão-monstro',
  'movimentação de caminhões',
  'caminhonete',
  'camiseta',
  'tty',
  'televisão',
  'guarda-chuva',
  'praia de guarda-sol',
  'sublinhado',
  'desfazer',
  'desfazer alt',
  'acesso universal',
  'universidade',
  'desligar',
  'desbloquear',
  'desbloquear alt',
  'Envio',
  'do utilizador',
  'user-alt',
  'user-alt-slash',
  'usuário-astronauta',
  'verificação do usuário',
  'círculo do usuário',
  'relógio do usuário',
  'user-cog',
  'edição do usuário',
  'amigos do usuário',
  'usuário graduado',
  'ferido pelo usuário',
  'bloqueio de usuário',
  'user-md',
  'usuário-menos',
  'usuário-ninja',
  'enfermeira usuária',
  'usuário mais',
  'segredo do usuário',
  'escudo do usuário',
  'barra do usuário',
  'tag de usuário',
  'laço de usuário',
  'tempos do usuário',
  'Comercial',
  'users-cog',
  'user-slash',
  'colher de utensílio',
  'utensílios',
  'vetor-quadrado',
  'Vênus',
  'Vênus duplo',
  'venus-mars',
  'colete',
  'remendos de colete',
  'frasco',
  'frascos',
  'vídeo',
  'video-slash',
  'vihara',
  'vírus',
  'vírus-barra',
  'vírus',
  'correio de voz',
  'bola de voleibol',
  'volume baixo',
  'volume-mudo',
  'volume desligado',
  'aumentar o volume',
  'vote sim',
  'cartão vr',
  'caminhando',
  'carteira',
  'armazém',
  'água',
  'onda quadrada',
  'peso',
  'suspensão de peso',
  'cadeira de rodas',
  'Wi-fi',
  'vento',
  'janela fechada',
  'maximização da janela',
  'minimizar janela',
  'janela-restauração',
  'garrafa de vinho',
  'copo de vinho',
  'taça de vinho alt',
  'sinal de ganho',
  'chave inglesa',
  'raio X',
  'símbolo do iene',
  'yin-yang',
];
